version: '3.8'

networks:
  minio_network:

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    volumes:
      - ./data:/data
      - ./certs:/root/.minio/certs  # TLS certificate and key go here
    ports:
      - "9000:9000"  # HTTPS S3 API
      - "9090:9090"  # HTTPS Console UI
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER:-minioadmin}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD:-minioadmin123}"
    command: server /data --console-address ":9090"
    networks:
      - minio_network
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-client:
    image: minio/mc:latest
    container_name: minio-client
    restart: always
    depends_on:
      - minio
    networks:
      - minio_network
    volumes:
      - ./mc-config:/root/.mc  # Optional: store `mc` config
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc config host rm minio;
      mc config host add --quiet --api s3v4 minio https://minio:9000 ${MINIO_ROOT_USER:-minioadmin} ${MINIO_ROOT_PASSWORD:-minioadmin123};
      sleep infinity;
      "
