version: '3'

networks:
  minio_network:

services:
  minio:
    container_name: minio
    image: minio/minio:latest
    volumes:
      - ./data:/data
      - ./certs:/root/.minio/certs  # TLS certificates
    ports:
      - "9000:9000"   # S3 API (HTTPS)
    networks:
      - minio_network
    restart: always
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-console:
    container_name: minio-console
    restart: always
    image: minio/console:latest
    ports:
      - "9090:9090"
    networks:
      - minio_network
    command: server
    environment:
      - CONSOLE_MINIO_SERVER=https://minio:9000
    depends_on:
      - minio

  minio-client:
    container_name: minio-client
    restart: always
    image: minio/mc:latest
    volumes:
      - ./config:/root/.mc
    depends_on:
      - minio
    networks:
      - minio_network
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc config host rm minio;
      mc config host add --quiet --api s3v4 minio https://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      sleep infinity;
      "
